# Global settings applied to the whole site.
# "base" is a directory to change to before starting build, and
# "publish" is the directory to publish (relative to root of your repo).
# "command" is your build command
[build]
    base    = ""
    publish = "build"
    command = "REACT_APP_STAGE=dev npm run build"
    
# Production context: All deploys to the main repository branch
# will inherit these changes.
[context.production]
    command = "REACT_APP_STAGE=prod npm run build"

# Deploy Preview context: All Deploy Previews will inherit these settings.
[context.deploy-preview]
    command = "REACT_APP_STAGE=dev npm run build"

# Branch Deploy context: All deploys that are not in an active
# Deploy Preview will inherit these settings
[context.branch-deploy]
    command = "REACT_APP_STAGE=dev npm run build"

# We’ll need to handle requests to any non-root paths of our app. 
# Our frontend is a single-page app and the routing is handled on the client side. 
# We need to tell Netlify to always redirect any request to our index.html and return the 200 status code for it.
[[redirects]]
    from    = "/*"
    to      = "/index.html"
    status  = 200